services:
  app:
    image: tuumik/tuumik:1.0.9
    ports:
      - '8082:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      PORT: 3000
      TZ: Etc/UTC
      METEOR_SETTINGS: |
        {
          "public": {
            "email": false,
            "demoMode": true,
            "composerLimit": 1000
          },
          "private": {
            "systemEmail": "noreply@exampledomain.com",
            "monitorEmail": "monitor@exampledomain.com",
            "disableSignupAfterSignup": false,
            "tenantDeletionByTenant": true
          }
        }

  mongo:
    image: mongo:6.0.3
    command: [--replSet, rs0, --port, "27017"]
    # delete the below healthcheck block after first run of mongo
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - /volume1/docker/tuumik/tuumikdb:/data/db
