services:
  app:
    image: tuumik/tuumik:1.0.12
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      ROOT_URL: https://tuumik.example.com
      MONGO_URL: mongodb://mongo:27017/meteor
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      PORT: 3000
      TZ: Etc/UTC
      METEOR_SETTINGS: |
        {
          "public": {
            "email": false,
            "demoMode": true,
            "composerLimit": 1000
          },
          "private": {
            "systemEmail": "noreply@exampledomain.com",
            "monitorEmail": "monitor@exampledomain.com",
            "disableSignupAfterSignup": false,
            "tenantDeletionByTenant": true
          }
        }

  mongo:
    image: mongo:7.0.16
    command: [--replSet, rs0, --port, "27017"]
    restart: unless-stopped
    volumes:
      - tuumikdb:/data/db

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  export:
    image: tuumik/tuumik-export:1.0.0
    restart: unless-stopped
    environment:
      API_KEY: tuumik

volumes:
  tuumikdb:
  caddy_data:
  caddy_config:
